//! Golden-string tests over the shared fixture conversation (see
//! `tests/common/mod.rs`), one per format. Fixture output files under
//! `tests/fixtures/` were generated by this exact renderer and hand-reviewed
//! line by line (empty-text segment skipped, zero-duration cue, 90-minute
//! `HH` rollover, `translation: Some` surfaced only in JSON, no-speaker
//! segment falling back to `Remote`) before being committed as the baseline;
//! a future change to any renderer's output must update them deliberately,
//! not accidentally.

mod common;

use fc_export::{export, ExportFormat, ExportOptions};

fn fixture(name: &str) -> String {
    std::fs::read_to_string(format!(
        "{}/tests/fixtures/{name}",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap_or_else(|e| panic!("reading fixture {name}: {e}"))
}

#[test]
fn text_plain() {
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Text,
        &ExportOptions::default(),
    );
    assert_eq!(out, fixture("text_plain.txt"));
}

#[test]
fn text_full_options() {
    let options = ExportOptions {
        timestamps: true,
        speakers: true,
        metadata: true,
    };
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Text,
        &options,
    );
    assert_eq!(out, fixture("text_full.txt"));
}

#[test]
fn markdown_full_options() {
    let options = ExportOptions {
        timestamps: true,
        speakers: true,
        metadata: true,
    };
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Markdown,
        &options,
    );
    assert_eq!(out, fixture("markdown_full.md"));
}

#[test]
fn json_plain() {
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Json,
        &ExportOptions::default(),
    );
    assert_eq!(out, fixture("json_plain.json"));
}

#[test]
fn json_full_options() {
    let options = ExportOptions {
        timestamps: true,
        speakers: true,
        metadata: true,
    };
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Json,
        &options,
    );
    assert_eq!(out, fixture("json_full.json"));
}

#[test]
fn srt_plain() {
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Srt,
        &ExportOptions::default(),
    );
    assert_eq!(out, fixture("srt_plain.srt"));
}

#[test]
fn srt_with_speakers() {
    let options = ExportOptions {
        speakers: true,
        ..Default::default()
    };
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Srt,
        &options,
    );
    assert_eq!(out, fixture("srt_speakers.srt"));
}

#[test]
fn vtt_full_options() {
    let options = ExportOptions {
        timestamps: true,
        speakers: true,
        metadata: true,
    };
    let out = export(
        &common::conversation(),
        &common::segments(),
        ExportFormat::Vtt,
        &options,
    );
    assert_eq!(out, fixture("vtt_full.vtt"));
}
